# Generated by Django 5.1.9 on 2025-05-22 11:59

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django_tenants.postgresql_backend.base
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('service_area', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='utility_logos/')),
                ('primary_color', models.CharField(default='#1f2937', max_length=7)),
                ('secondary_color', models.CharField(default='#3b82f6', max_length=7)),
                ('subscription_tier', models.CharField(choices=[('basic', 'Basic'), ('professional', 'Professional'), ('enterprise', 'Enterprise')], default='basic', max_length=20)),
                ('max_field_agents', models.PositiveIntegerField(default=10)),
                ('max_assets', models.PositiveIntegerField(default=1000)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Water Utility',
                'verbose_name_plural': 'Water Utilities',
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='tenants.utility')),
            ],
            options={
                'verbose_name': 'Utility Domain',
                'verbose_name_plural': 'Utility Domains',
            },
        ),
    ]
