# Generated by Django 5.1.9 on 2025-05-24 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utility',
            name='deleted_on',
            field=models.DateTimeField(blank=True, help_text='When utility was soft deleted', null=True),
        ),
        migrations.AddField(
            model_name='utility',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft delete flag'),
        ),
    ]
