# Generated by Django 5.1.9 on 2025-05-24 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('infrastructure', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetdocument',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='infrastructure.asset'),
        ),
        migrations.AddField(
            model_name='assetdocument',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetphoto',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='infrastructure.asset'),
        ),
        migrations.AddField(
            model_name='assetphoto',
            name='taken_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='infrastructure.assettype'),
        ),
        migrations.AddField(
            model_name='meter',
            name='asset',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meter_details', to='infrastructure.asset'),
        ),
        migrations.AddField(
            model_name='pipe',
            name='end_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_pipes', to='infrastructure.asset'),
        ),
        migrations.AddField(
            model_name='pipe',
            name='start_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_pipes', to='infrastructure.asset'),
        ),
        migrations.AddField(
            model_name='valve',
            name='asset',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='valve_details', to='infrastructure.asset'),
        ),
        migrations.AddField(
            model_name='valve',
            name='operated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='zone',
            name='inlet_meters',
            field=models.ManyToManyField(blank=True, related_name='inlet_zones', to='infrastructure.meter'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['asset_id'], name='assets_asset_i_6c35ce_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['status'], name='assets_status_326766_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['asset_type'], name='assets_asset_t_57ae73_idx'),
        ),
        migrations.AddIndex(
            model_name='pipe',
            index=models.Index(fields=['pipe_id'], name='pipes_pipe_id_3488f0_idx'),
        ),
        migrations.AddIndex(
            model_name='pipe',
            index=models.Index(fields=['material'], name='pipes_materia_c3f2e8_idx'),
        ),
    ]
