# Generated by Django 5.1.9 on 2025-05-24 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer_support', '0001_initial'),
        ('infrastructure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='meter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_connection', to='infrastructure.meter'),
        ),
        migrations.AddField(
            model_name='customer',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='infrastructure.zone'),
        ),
    ]
